apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cantondex

commonLabels:
  app.kubernetes.io/instance: cantondex
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: cantondex

commonAnnotations:
  managed-by: terraform

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secrets-template.yaml
  - deployments.yaml
  - services.yaml
  - ingress.yaml
  - hpa.yaml

replicas:
  - name: api-gateway
    count: 3
  - name: matching-engine
    count: 3
  - name: settlement-coordinator
    count: 2
  - name: risk-management
    count: 2
  - name: notification-service
    count: 2
  - name: compliance-service
    count: 2

images:
  - name: DOCKER_REGISTRY/cantondex/api-gateway
    newName: DOCKER_REGISTRY/cantondex/api-gateway
    newTag: latest
  - name: DOCKER_REGISTRY/cantondex/matching-engine
    newName: DOCKER_REGISTRY/cantondex/matching-engine
    newTag: latest
  - name: DOCKER_REGISTRY/cantondex/settlement-coordinator
    newName: DOCKER_REGISTRY/cantondex/settlement-coordinator
    newTag: latest
  - name: DOCKER_REGISTRY/cantondex/risk-management
    newName: DOCKER_REGISTRY/cantondex/risk-management
    newTag: latest
  - name: DOCKER_REGISTRY/cantondex/notification-service
    newName: DOCKER_REGISTRY/cantondex/notification-service
    newTag: latest
  - name: DOCKER_REGISTRY/cantondex/compliance-service
    newName: DOCKER_REGISTRY/cantondex/compliance-service
    newTag: latest
